In [45]:
# dependencies
"""
Numpy: matrix manipulation and math
Pandas: csv parsing and various data structure tasks
Mathpltlib.pyplot: data visualization
set_trace: debug breaks
keras: a machine learning library that is intuitive to read
tensorflow: backend for keras... also the most widely used machine learning library
re: regular expressions
"""
from copy import deepcopy as copy
from IPython.core.debugger import set_trace

import sys
import numpy as np
import pandas as pd
import scipy.special as sci
import matplotlib.pyplot as plt 
import os
import tensorflow as tf
import keras
# not needed
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation

tf.config.optimizer.set_jit(True) # optimizes cpu usage

import re
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline

In [3]:
"""
concat_files
----------

Concatenate text files in a directory as a string

dependent on 'os' Python module

parameters
----------
directory: string; path of the target directory

f_type:    tuple of strings; target file extentsions Ex: ('.py', '.cpp')

return
---------
content:   concatenated string

"""
def concat_files(directory,f_type):
    import os
    # List all file in the dataset directory
    # ------------------
    all_file = []
    content = ""

    # walk through every directory and open every f_type file
    # concatenate into var string "content"
    for root, dirs, files in os.walk(directory): 
        for name in files:
            if name.endswith(f_type): # we only care about .py
                all_file.append(name)
                with open(os.path.join(root,name), "r",encoding="utf8") as f:
                    content += f.read() + "\n"
    return content

In [4]:
content = concat_files("dataset",('.py'))

In [5]:
r_all_ascii = "[^\x00-\x7F]"

In [14]:
"""
encode_string
-----------
Generate a dictionary representation of the characters found 
in a string keyed with integer representations

Returns two dictionaries and an array. The two dictionaries are 
necessary to convert the string to integer representation
and back again. The array is the string encoded as integer values.

parameters
----------
content:      string; to be processed

return
----------
vocab_to_int: dict; character to integer representation of unique characters in the string

int_to_vocab: dict; integer to string representation

encoded:      array; string encoded as integer values
"""

def encode_string(content):   
    # Convert the string "content" into a list of intergers

    ### creates a set of the individual characters
    vocab = set(content)
    ### attempt to clean out non-ascii characters
    vocab_c = copy(vocab)
    for i, char in enumerate(vocab_c):
        if re.search(r_all_ascii,char):
            vocab.remove(char)
    print(vocab)
    print(len(vocab))
    ### use the set to sequentially generate a dictionary
    vocab_to_int = {c: i for i, c in enumerate(vocab)} 
    print(vocab_to_int)
    ### make keys the numerical values
    int_to_vocab = dict(enumerate(vocab)) 
    
    ### encode the "content" string using dict
    ### encoded = np.array([vocab_to_int[c] for c in content], dtype=np.int32)
    
    # *** Uncomment the below lines if you haven't saved the encoded array
    # Then rerun cell
#   -------------------------------------------------
#     encoded = np.array([],dtype=np.int16)
#     for c in content:
#         if c in vocab_to_int:
#             encoded = np.append(encoded,vocab_to_int[c])
#   -------------------------------------------------
    encoded = np.load('./encoded.npy') # comment out if above lines are uncommented
    
    return vocab_to_int, int_to_vocab, encoded

In [7]:
vocab_to_int, int_to_vocab, encoded = encode_string(content)

{'%', 'P', '\n', '`', '~', 'w', '0', 'u', 'N', '9', '&', 'd', 'F', 'R', '<', 'z', ',', 'M', ']', '/', 't', 'k', 'o', 'L', '8', ':', 'Q', 'W', 'g', '6', '$', '#', '2', 'v', '@', 'i', ' ', 'O', '[', 'I', '>', 'r', 'B', 'E', 'q', 'S', 'K', 'l', 'e', 'C', '^', '|', '*', 'f', 'b', 'p', 'a', ')', 'x', '+', '5', '(', '3', "'", '7', '!', 'j', 'm', 'T', '{', ';', '}', '"', 'Y', 'c', 'U', 'D', '-', '?', '\\', 's', 'J', '1', 'h', 'H', 'G', '\t', '_', 'A', '4', 'X', '=', 'Z', 'y', '.', 'n', 'V'}
97
{'%': 0, 'P': 1, '\n': 2, '`': 3, '~': 4, 'w': 5, '0': 6, 'u': 7, 'N': 8, '9': 9, '&': 10, 'd': 11, 'F': 12, 'R': 13, '<': 14, 'z': 15, ',': 16, 'M': 17, ']': 18, '/': 19, 't': 20, 'k': 21, 'o': 22, 'L': 23, '8': 24, ':': 25, 'Q': 26, 'W': 27, 'g': 28, '6': 29, '$': 30, '#': 31, '2': 32, 'v': 33, '@': 34, 'i': 35, ' ': 36, 'O': 37, '[': 38, 'I': 39, '>': 40, 'r': 41, 'B': 42, 'E': 43, 'q': 44, 'S': 45, 'K': 46, 'l': 47, 'e': 48, 'C': 49, '^': 50, '|': 51, '*': 52, 'f': 53, 'b': 54, 'p': 55, 'a': 56, ')'

## $\rightarrow$ Save encoded array to avoid heavy computation

In [8]:
#from tempfile import TemporaryFile as TF
outfile = "./encoded"

np.save(outfile,encoded)

In [9]:
#print(content)
print(int_to_vocab)
# this is all of the files concatenated. with each character encoded using the int_to_vocab
print(encoded)

{0: '%', 1: 'P', 2: '\n', 3: '`', 4: '~', 5: 'w', 6: '0', 7: 'u', 8: 'N', 9: '9', 10: '&', 11: 'd', 12: 'F', 13: 'R', 14: '<', 15: 'z', 16: ',', 17: 'M', 18: ']', 19: '/', 20: 't', 21: 'k', 22: 'o', 23: 'L', 24: '8', 25: ':', 26: 'Q', 27: 'W', 28: 'g', 29: '6', 30: '$', 31: '#', 32: '2', 33: 'v', 34: '@', 35: 'i', 36: ' ', 37: 'O', 38: '[', 39: 'I', 40: '>', 41: 'r', 42: 'B', 43: 'E', 44: 'q', 45: 'S', 46: 'K', 47: 'l', 48: 'e', 49: 'C', 50: '^', 51: '|', 52: '*', 53: 'f', 54: 'b', 55: 'p', 56: 'a', 57: ')', 58: 'x', 59: '+', 60: '5', 61: '(', 62: '3', 63: "'", 64: '7', 65: '!', 66: 'j', 67: 'm', 68: 'T', 69: '{', 70: ';', 71: '}', 72: '"', 73: 'Y', 74: 'c', 75: 'U', 76: 'D', 77: '-', 78: '?', 79: '\\', 80: 's', 81: 'J', 82: '1', 83: 'h', 84: 'H', 85: 'G', 86: '\t', 87: '_', 88: 'A', 89: '4', 90: 'X', 91: '=', 92: 'Z', 93: 'y', 94: '.', 95: 'n', 96: 'V'}
[48 59 31 ... 55 56 56]


## First data process attempt

In [32]:

segment = [500,1000,1500,2000]
# for i in range(500): 
#     segment.append((int(len(encoded) / 500) * (i + 1)))
batch = {
    "x" : [
        encoded[:segment[0]],
        encoded[segment[0]:segment[1]]
    ],
    "y" : [
        encoded[1:segment[0]+1],
        encoded[segment[0]+1:segment[1]+1]
    ]
}

In [61]:
# inp = np.vstack((batch['x'][0],batch['x'][1]))
# targets = np.vstack((batch['y'][0],batch['y'][1]))
inp = batch['x'][0]
targets = batch['y'][0]
Xtest = batch['x'][1]
Ttest = batch['y'][1]
io_size = len(int_to_vocab)

# inp = np.hstack((np.ones((Xtest.shape[0],1)),tf.one_hot(inp,io_size)))
# targets = np.hstack((np.ones((Xtest.shape[0],1)),tf.one_hot(targets,io_size)))
# Xtest = np.hstack((np.ones((Xtest.shape[0],1)),tf.one_hot(Xtest,io_size)))
# Ttest = np.hstack((np.ones((Xtest.shape[0],1)),tf.one_hot(Ttest,io_size)))

inp = tf.one_hot(inp,io_size)
targets = tf.one_hot(targets,io_size)
Xtest = tf.one_hot(Xtest,io_size)
Ttest = tf.one_hot(Ttest,io_size)

# encoded_as_i = np.hstack((np.ones((1,1)),tf.one_hot(encoded[:1],io_size)))
encoded_as_i = tf.one_hot(encoded[:500],io_size)

#tf.print(Xtest, summarize=50)
print(inp.shape)

# inp = tf.expand_dims(inp,2)
# targets = tf.expand_dims(targets,2)

(500, 97)


In [109]:
# lines = []
# temp = []
# for i, char in enumerate(encoded):
#     if int_to_vocab[char] == '\n':
#         lines.append(temp)
#     else:
#         temp.append(char)
#         temp = []

# x = np.zeros((len(lines), maxlen, len(int_to_vocab)), dtype=np.bool)
# y = np.zeros((len(sentences), len(int_to_vocab)), dtype=np.bool)
# for i, sentence in enumerate(sentences):
#     for t, char in enumerate(sentence):
#         x[i, t, char_indices[char]] = 1
#     y[i, char_indices[next_chars[i]]] = 1

## Second data processing attempt

In [17]:
n_chars = len(encoded)
n_vocab = len(vocab_to_int)
seq_len = 100
datax = []
datay = []
for i in range(0, n_chars - seq_len, 1):
    seq_in = encoded[i:i + seq_len]
    seq_out = encoded[i + seq_len]
    datax.append(seq_in)
    datay.append(seq_out)
n_patterns = len(datax)
print("Total patterns: ", n_patterns)
print("Total unique characters: ", n_vocab)

Total patterns:  1114909
Total unique characters:  97


In [24]:
from keras.utils import np_utils
X = np.reshape(datax, (n_patterns,seq_len,1))
X = X / float(n_vocab)
Y = np_utils.to_categorical(datay)
print(Y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.optimizers import RMSprop, SGD

# x_train = np.hstack((batch['x'][0],batch['x'][1]))
# y_train = np.hstack((batch['y'][0],batch['y'][1]))
# x_test = np.hstack((batch['x'][0],batch['x'][1]))
# y_test = np.hstack((batch['y'][0],batch['y'][1]))

max_features = 97
#maxlen = 40

model = Sequential()
model.add(LSTM(256, input_shape=(X.shape[1], X.shape[2])))
model.add(Dropout(0.2))
model.add(Dense(Y.shape[1], activation='softmax'))

# optimizer = RMSprop(learning_rate=0.05)

# model.compile(loss='categorical_crossentropy',
#               optimizer=optimizer,
#               metrics=['accuracy'])

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [33]:
# checkpoint
from tensorflow.keras.callbacks import ModelCheckpoint
filepath = "weights-improvement-{epoch:02d}-{loss:4f}.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='loss',verbose=1, save_best_only=True, mode='min')
callback_list = [checkpoint]

In [35]:
# model.fit(inp, targets, steps_per_epoch=10, epochs=10)
#model.get_weights().shape

model.fit(X[:60000] , Y[:60000], epochs=20, batch_size=128, callbacks=callback_list)

Train on 60000 samples
Epoch 1/20
59776/60000 [============================>.] - ETA: 0s - loss: 1.6449 - accuracy: 0.5614
Epoch 00001: loss improved from inf to 1.64610, saving model to weights-improvement-01-1.646096.hdf5
60000/60000 [==============================] - 13s 220us/sample - loss: 1.6461 - accuracy: 0.5611
Epoch 2/20
59776/60000 [============================>.] - ETA: 0s - loss: 1.6216 - accuracy: 0.5684
Epoch 00002: loss improved from 1.64610 to 1.62152, saving model to weights-improvement-02-1.621522.hdf5
60000/60000 [==============================] - 12s 207us/sample - loss: 1.6215 - accuracy: 0.5684
Epoch 3/20
59776/60000 [============================>.] - ETA: 0s - loss: 1.5603 - accuracy: 0.5826
Epoch 00003: loss improved from 1.62152 to 1.55995, saving model to weights-improvement-03-1.559948.hdf5
60000/60000 [==============================] - 13s 211us/sample - loss: 1.5599 - accuracy: 0.5827
Epoch 4/20
59776/60000 [============================>.] - ETA: 0s - loss

In [36]:
from tensorflow.keras.models import load_model
# model.save('.\model')
score = model.evaluate(X[60000:120000], Y[60000:120000])
print(score)

60000/60000 [==============================] - 14s 242us/sample - loss: 3.1916 - accuracy: 0.2831
[3.191573794937134, 0.28306666]


## First attempt at testing model

In [67]:
# print(tf.keras.backend.shape(Xtest),tf.keras.backend.shape(model.weights))
# sci.softmax(Xtest @ encoded_to_i)
print(encoded_as_i)
print(tf.convert_to_tensor(model.predict(encoded_as_i, steps=1, verbose=0)))
print(np.argmax(model.predict(encoded_as_i, steps=3, verbose=0),axis=1))
print(np.sum(model.predict(encoded_as_i, steps=3, verbose=0)[0]))
nextc = int_to_vocab[np.argmax(model.predict(encoded_as_i, steps=3, verbose=0),axis=1)[1]]
print(nextc) # should give probabilities of next character
print()

tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(500, 97), dtype=float32)
tf.Tensor(
[[1.6083467e-07 1.5905206e-01 1.6123180e-07 ... 6.8660093e-08
  4.9035528e-08 3.6955536e-03]
 [1.6079790e-07 1.5846752e-01 1.6122462e-07 ... 6.8636282e-08
  4.9024273e-08 3.7028429e-03]
 [1.6086379e-07 1.5974109e-01 1.6122148e-07 ... 6.8684187e-08
  4.9045525e-08 3.6875154e-03]
 ...
 [1.6086251e-07 1.5962288e-01 1.6122836e-07 ... 6.8681082e-08
  4.9044623e-08 3.6887384e-03]
 [1.6070277e-07 1.5707102e-01 1.6119995e-07 ... 6.8576917e-08
  4.8995503e-08 3.7204761e-03]
 [1.6331968e-07 1.5637104e-01 1.6368018e-07 ... 6.9626587e-08
  4.9744887e-08 3.7324438e-03]], shape=(500, 97), dtype=float32)
[50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 

In [63]:
strout = ""
data = Xtest
#actual = ""
predict = np.argmax(model.predict(data, steps=500, verbose=0),axis=1)
print(predict)
for i in predict:
    
    nextc = int_to_vocab[predict[i]]
    
    #actual += int_to_vocab[data[i]]
    strout += nextc
print(strout)
#print(actual)


[50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50

## Second attempt at testing model

### Load best weights recorded from training 

In [37]:
filename = "weights-improvement-19-1.168981.hdf5"
model.load_weights(filename)
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [86]:

# pick a random seed
start = np.random.randint(0, len(datax)-1)
pattern = []
pattern = datax[start]
print("Seed:")
print ("\"", ''.join([int_to_vocab[value] for value in pattern]), "\"")
# generate characters
for i in range(1000):
    x = np.reshape(pattern, (1, len(pattern), 1))
    x = x / float(n_vocab)
    prediction = model.predict(x, verbose=0)
    index = np.argmax(prediction)
    result = int_to_vocab[index]
    seq_in = [int_to_vocab[value] for value in pattern]
    sys.stdout.write(result)
    np.hstack((pattern, [index])) # TODO make so length of pattern is 101, as it should be
    length = len(pattern) 
    print("length of: " ,len(pattern))
    pattern = pattern[1:length + 1] # issue with the length. no matter what, length of pattern become 99
print ("\nDone.")

Seed:
" =)&\ia^^^^PuEM1!Q=6^PuEMb! =^U^E1&,MPuE:=)&\iaa^^^^e^=i0^dPqqi1iO0^\!PO0=^0!^1!0&0i^Pu&Eia^^^^\0=V^U "
7100
length of:  100


ValueError: Error when checking input: expected lstm_input to have shape (100, 1) but got array with shape (99, 1)

# References

1. [LSTM: A search space odyssey](https://arxiv.org/pdf/1503.04069.pdf?utm_content=buffereddc5&utm_medium=social&utm_source=plus.google.com&utm_campaign=buffer)