In [2]:
# dependencies
"""
Numpy: matrix manipulation and math
Pandas: csv parsing and various data structure tasks
Mathpltlib.pyplot: data visualization
set_trace: debug breaks
keras: a machine learning library that is intuitive to read
tensorflow: backend for keras... also the most widely used machine learning library
re: regular expressions
"""
from copy import deepcopy as copy
from IPython.core.debugger import set_trace

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import os
import tensorflow as tf
import keras
# not needed
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation

tf.config.optimizer.set_jit(True) # optimizes cpu usage

import re
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline

Using TensorFlow backend.


In [3]:
"""
concat_files
----------

Concatenate text files in a directory as a string

dependent on 'os' Python module

parameters
----------
directory: string; path of the target directory

f_type:    tuple of strings; target file extentsions Ex: ('.py', '.cpp')

return
---------
content:   concatenated string

"""
def concat_files(directory,f_type):
    import os
    # List all file in the dataset directory
    # ------------------
    all_file = []
    content = ""

    # walk through every directory and open every f_type file
    # concatenate into var string "content"
    for root, dirs, files in os.walk(directory): 
        for name in files:
            if name.endswith(f_type): # we only care about .py
                all_file.append(name)
                with open(os.path.join(root,name), "r") as f:
                    content += f.read() + "\n"
    return content

In [4]:
content = concat_files("dataset",('.py'))

In [5]:
r_all_ascii = "[^\x00-\x7F]"

In [6]:
"""
encode_string
-----------
Generate a dictionary representation of the characters found 
in a string keyed with integer representations

Returns two dictionaries and an array. The two dictionaries are 
necessary to convert the string to integer representation
and back again. The array is the string encoded as integer values.

parameters
----------
content:      string; to be processed

return
----------
vocab_to_int: dict; character to integer representation of unique characters in the string

int_to_vocab: dict; integer to string representation

encoded:      array; string encoded as integer values
"""

def encode_string(content):   
    # Convert the string "content" into a list of intergers
    
    # creates a set of the individual characters
    vocab = set(content)
    # attempt to clean out non-ascii characters
#     vocab_c = vocab.copy()
#     for i, char in enumerate(vocab_c):
#         if re.search(r_all_ascii,char):
#             vocab.remove(char)
#     print(vocab)
#     print(len(vocab))
    # use the set to sequentially generate a dictionary
    vocab_to_int = {c: i for i, c in enumerate(vocab)} 
    
    # make keys the numerical values
    int_to_vocab = dict(enumerate(vocab)) 
    
    # encode the "content" string using dict
    encoded = np.array([vocab_to_int[c] for c in content], dtype=np.int32)
    
    return vocab_to_int, int_to_vocab, encoded

In [7]:
vocab_to_int, int_to_vocab, encoded = encode_string(content)

In [8]:
#print(content)
print(int_to_vocab)
# this is all of the files concatenated. with each character encoded using the int_to_vocab
print(encoded)

{0: 's', 1: '|', 2: '<', 3: 'u', 4: '≥', 5: '>', 6: '?', 7: ',', 8: 'S', 9: 'Q', 10: '√', 11: '_', 12: 'l', 13: '维', 14: 'j', 15: 'K', 16: 'X', 17: '！', 18: '5', 19: 'F', 20: 'T', 21: '下', 22: '到', 23: 'V', 24: 'ł', 25: '[', 26: "'", 27: '~', 28: 'e', 29: '9', 30: '‘', 31: '½', 32: 'i', 33: 'W', 34: '@', 35: 'q', 36: '度', 37: 'o', 38: 'p', 39: 'A', 40: '–', 41: '≤', 42: 'r', 43: 'ü', 44: 'b', 45: '×', 46: '`', 47: '\t', 48: '!', 49: 'E', 50: '£', 51: '😁', 52: 'Z', 53: '}', 54: '$', 55: '’', 56: ')', 57: 'R', 58: '=', 59: 'ã', 60: '1', 61: '#', 62: '（', 63: 'O', 64: 'L', 65: '≠', 66: 'g', 67: 'h', 68: 'D', 69: '6', 70: '-', 71: '：', 72: '3', 73: 'z', 74: 'Å', 75: '−', 76: ']', 77: '.', 78: 'µ', 79: '4', 80: 'm', 81: '/', 82: '精', 83: 'f', 84: 'y', 85: '，', 86: '*', 87: '"', 88: ' ', 89: '达', 90: 'k', 91: '🤓', 92: 'c', 93: '午', 94: '^', 95: '²', 96: '(', 97: 'C', 98: 'a', 99: '8', 100: '\n', 101: ';', 102: 'n', 103: 'w', 104: '2', 105: 'I', 106: '→', 107: 'J', 108: 'd', 109: '+', 110: 'U

In [35]:
segment = [10,20,30,40]
# for i in range(500): 
#     segment.append((int(len(encoded) / 500) * (i + 1)))
batch = {
    "x" : [
        encoded[:segment[0]],
        encoded[segment[0]:segment[1]]
    ],
    "y" : [
        encoded[segment[1]:segment[2]],
        encoded[segment[2]:segment[3]]
    ]
}

In [36]:
# inp = np.vstack((batch['x'][0],batch['x'][1]))
# targets = np.vstack((batch['y'][0],batch['y'][1]))
inp = batch['x'][0]
targets = batch['y'][0]
io_size = len(int_to_vocab)

inp = tf.one_hot(inp,io_size)
targets = tf.one_hot(targets,io_size)
tf.print(inp, summarize=50)
print(inp.shape)

# inp = tf.expand_dims(inp,2)
# targets = tf.expand_dims(targets,2)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [109]:
# lines = []
# temp = []
# for i, char in enumerate(encoded):
#     if int_to_vocab[char] == '\n':
#         lines.append(temp)
#     else:
#         temp.append(char)
#         temp = []

# x = np.zeros((len(lines), maxlen, len(int_to_vocab)), dtype=np.bool)
# y = np.zeros((len(sentences), len(int_to_vocab)), dtype=np.bool)
# for i, sentence in enumerate(sentences):
#     for t, char in enumerate(sentence):
#         x[i, t, char_indices[char]] = 1
#     y[i, char_indices[next_chars[i]]] = 1

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.layers import Embedding
from keras.layers import LSTM
from keras.optimizers import RMSprop, SGD

# x_train = np.hstack((batch['x'][0],batch['x'][1]))
# y_train = np.hstack((batch['y'][0],batch['y'][1]))
# x_test = np.hstack((batch['x'][0],batch['x'][1]))
# y_test = np.hstack((batch['y'][0],batch['y'][1]))

max_features = 1024
#maxlen = 40

model = Sequential()
model.add(Embedding(max_features, output_dim=256))
model.add(LSTM(10, input_shape=inp.shape))
model.add(Dropout(0.5))
model.add(Dense(io_size, activation='softmax'))

optimizer = RMSprop(learning_rate=0.01)

model.compile(loss='categorical_crossentropy',
              optimizer=optimizer,
              metrics=['accuracy'])

model.fit(inp, targets, steps_per_epoch=133, epochs=10)
score = model.evaluate(inp, targets, steps_per_epoch=133)

/home/bran/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Epoch 1/10
133/133 [==============================] - 41s 309ms/step - loss: 2.3270 - accuracy: 0.1729
Epoch 2/10
133/133 [==============================] - 39s 292ms/step - loss: 2.0558 - accuracy: 0.2045
Epoch 3/10
133/133 [==============================] - 38s 284ms/step - loss: 2.0519 - accuracy: 0.2023
Epoch 4/10
133/133 [==============================] - 39s 294ms/step - loss: 2.0448 - accuracy: 0.1940
Epoch 5/10
133/133 [==============================] - 38s 288ms/step - loss: 2.0352 - accuracy: 0.1917
Epoch 6/10
133/133 [==============================] - 39s 296ms/step - loss: 2.0367 - accuracy: 0.2113
Epoch 7/10
 17/133 [==>...........................] - ETA: 37s - loss: 2.0366 - accuracy: 0.1941